version: "3"
services:

  mesh:
    image: gentics/mesh:1.3.1
    environment:
      - MESH_ELASTICSEARCH_URL=http://elasticsearch:9200
      - MESH_ELASTICSEARCH_START_EMBEDDED=false
      - MESH_AUTH_KEYSTORE_PASS=changeme
      - MESH_GRAPH_DB_DIRECTORY=null
      - MESH_MONITORING_ENABLED=false
      - MESH_HTTP_CORS_ENABLE=true
      - MESH_INITIAL_ADMIN_PASSWORD=admin
      - MESH_INITIAL_ADMIN_PASSWORD_FORCE_RESET=false
      - MESH_HTTP_CORS_ORIGIN_PATTERN=http://localhost:3000|http://localhost:3010
      - MESH_HTTP_CORS_ALLOW_CREDENTIALS=true
    ports:
      - '8080:8080'
#    volumes:
#      - ./data:/graphdb
#      - ./uploads:/uploads
#      - ./keystore:/keystore
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    depends_on:
      - elasticsearch
      - keycloak

  keycloak:
    image: jboss/keycloak:8.0.1
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - '127.0.0.1:8082:8080'
    command: [
        "-b",
        "0.0.0.0",
        "-Dkeycloak.migration.usersExportStrategy=SAME_FILE",
        "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING",
        "-Dkeycloak.import=/opt/jboss/keycloak/realm.json" 
      ]
    volumes:
      - ./keycloak/realm.json:/opt/jboss/keycloak/realm.json


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.5.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '127.0.0.1:9200:9200'
#    volumes:
#    - ./es:/usr/share/elasticsearch/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1

  app:
    build: ./frontend
    image: musetech-frontend:latest
    ports:
      - '3010:80'
    depends_on:
      - mesh

